# Holesovice config
# Extends the mainnet preset
PRESET_BASE: 'mainnet'

# Free-form short name of the network that this configuration applies to
# Must match the regex: [a-z0-9\-]
CONFIG_NAME: 'piertwodevnet'

# Transition
# ---------------------------------------------------------------
# Estimated on Sept 15, 2023
TERMINAL_TOTAL_DIFFICULTY: 0
# By default, don't use these params
TERMINAL_BLOCK_HASH: 0x1ccc0533bc2b7c6d0d210fef1108ef175cc71d3dcf22ed61a42632b1fe74e190
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0  # Sep 15, 2023, 2pm UTC


# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 8
# Sep 15, 2023, 2pm UTC
MIN_GENESIS_TIME: 1686477920
# Mainnet initial fork version, recommend altering for testnets
GENESIS_FORK_VERSION: 0x00186112
# 3600 seconds (1 hour)
GENESIS_DELAY: 160


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x01186112
ALTAIR_FORK_EPOCH: 0  # Sep 15, 2023, 2pm UTC
# Bellatrix
BELLATRIX_FORK_VERSION: 0x02186112
BELLATRIX_FORK_EPOCH: 0  # Sep 15, 2023, 2pm UTC
# Capella
CAPELLA_FORK_VERSION: 0x03186112
CAPELLA_FORK_EPOCH: 0  # Disabled
# EIP4844
EIP4844_FORK_VERSION: 0x04186112
EIP4844_FORK_EPOCH: 18446744073709551615  # Disabled

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 14 (estimate from proof-of-work mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 256 Eth1 blocks ~1 hour
ETH1_FOLLOW_DISTANCE: 256


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 32


# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
# PierTwo Testnet
DEPOSIT_CHAIN_ID: 1040404
DEPOSIT_NETWORK_ID: 1040404
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
